### ISSUE TITLE
Incorrect lang folder location

### ISSUE THREAD

**Issue by wruizcanal** [manadinho/lara-translate#1]
Please add a key to the configuration file to modify the location of the lang folder. In Laravel 10 the lang folder is located in the root of the project and not in the resources folder.

**Comment by manadinho** [comment]
Hi there,

Thank you for bringing this to my attention. I understand the importance of accommodating the changes in Laravel 10, especially regarding the location of the lang folder. I appreciate your suggestion to add a key to the configuration file for modifying the lang folder's location.

I've scheduled to work on this update over the weekend. Once the necessary changes are made, I'll update the repository and notify you. Your patience and contribution to improving this project are greatly appreciated.

Best regards,
Manadinho
